# -*- coding: utf-8 -*-
"""21BRS1217_Mall Customer Segmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hiER5uLndnZ0mdqSBJVVI2XOXNnVf2fF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans

"""Data Collection and Analysis"""

#Loading the data from csv file to the pandas Dataframe
customer_data=pd.read_csv('/content/Mall_Customers.csv')

customer_data.head()

customer_data.shape

customer_data.info()

customer_data.isnull().sum()

"""Selectiong the Annual Income and Spending Score column"""

X=customer_data.iloc[:,[3,4]].values

print(X)

"""Selecting the Number of clusters

WCSS-->Within Clusters Sum of Squares
"""

wcss=[]
for i in range(1,11):
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(X)

  wcss.append(kmeans.inertia_)

#plot an elbow graph

sns.set()
plt.plot(range(1,11),wcss)
plt.title('The Elbow Point Graph')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

"""Optimum Number of Clusters =5

Training the k-Means Clustering Model
"""

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=0)
Y=kmeans.fit_predict(X)

print(Y)

"""Visualizing all the Clusters"""

plt.figure(figsize=(8,8))
plt.scatter(X[Y==0,0],X[Y==0,1],s=50,c='green',label='Cluster1')
plt.scatter(X[Y==1,0],X[Y==1,1],s=50,c='red',label='Cluster2')
plt.scatter(X[Y==2,0],X[Y==2,1],s=50,c='yellow',label='Cluster3')
plt.scatter(X[Y==3,0],X[Y==3,1],s=50,c='violet',label='Cluster4')
plt.scatter(X[Y==4,0],X[Y==4,1],s=50,c='blue',label='Cluster5')

#plot the centroids

plt.scatter(kmeans.cluster_centers_[:,0],kmeans.cluster_centers_[:,1],s=100,c='cyan',label='Centroids')

plt.title('Customer Groups')
plt.xlabel('Annual Income')
plt.ylabel('Spending Score')
plt.show()